### ISSUE TITLE
Nil pointer exception in doGet

### ISSUE THREAD

**Issue by wxb2744** [wxb2744/ontap-go-client#4]
```
=== RUN   TestAccAggregateDataSource
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9f7d86]

goroutine 88 [running]:
github.com/wxb2744/ontap-client.(*OntapClient).doGet(0xc00010f7e0, 0x145a1e0, 0xc0006401e0, 0x12a5ae4, 0x13, 0xc000687430, 0xc000687510, 0x4, 0x4, 0x0, ...)
        /home/warrenb/go/src/netapp/terraform/vendor/github.com/wxb2744/ontap-client/client.go:268 +0x726
github.com/wxb2744/ontap-client.(*OntapClient).AggregateCollectionGet(0xc00010f7e0, 0x145a1e0, 0xc0006401e0, 0xc000687430, 0xc000687510, 0x4, 0x4, 0xc00066e910, 0xc00066e920, 0x1072fa0)
        /home/warrenb/go/src/netapp/terraform/vendor/github.com/wxb2744/ontap-client/api_storage.go:15 +0xaf
github.com/wxb2744/ontap-terraform-provider/ontap.dataSourceAggregateRead(0x145a1e0, 0xc0006401e0, 0xc00068c300, 0x1293360, 0xc00010f7e0, 0xc00066e980, 0xc000687950, 0x40ffb8)
        /home/warrenb/go/src/netapp/terraform/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1105 +0x4d4
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc00000e940, 0x145a160, 0xc000696040, 0xc000664000, 0xc00000e940, 0xc00006bba0, 0x472207)
        /home/warrenb/go/src/netapp/terraform/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:246 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x12348a0, 0xc00000e940, 0x145a220, 0xc000642000, 0xc000640000, 0x0, 0x145a220, 0xc000642000, 0xc00001e000, 0x7e)  
        /home/warrenb/go/src/netapp/terraform/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000016000, 0x1466720, 0xc000354f00, 0xc0005bc100, 0xc00022c090, 0x1ad1670, 0x0, 0x0, 0x0)
        /home/warrenb/go/src/netapp/terraform/vendor/google.golang.org/grpc/server.go:1210 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000016000, 0x1466720, 0xc000354f00, 0xc0005bc100, 0x0)
        /home/warrenb/go/src/netapp/terraform/vendor/google.golang.org/grpc/server.go:1533 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000344d90, 0xc000016000, 0x1466720, 0xc000354f00, 0xc0005bc100)
        /home/warrenb/go/src/netapp/terraform/vendor/google.golang.org/grpc/server.go:871 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/warrenb/go/src/netapp/terraform/vendor/google.golang.org/grpc/server.go:869 +0x1fd
exit status 2
FAIL    github.com/wxb2744/ontap-terraform-provider/ontap       2.326s
````

**Comment by wxb2744** [comment]
Caused by: -

```
265	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
266		var e ErrorResponse
267		err = json.Unmarshal(body, &e)
268		return nil, errors.New(*e.Error.Message)
269	}
```

Result of not checking the error value from json.Unmarshall

**Comment by wxb2744** [comment]
Problem caused by whitespace in URL. Imported net/url and used that to build, and properly escape, URLs
